### ISSUE TITLE
list-syscalls is missing

### ISSUE THREAD

**Issue by ebadi** [hrw/syscalls-table#10]
`list-syscalls.c` is mentioned in https://github.com/hrw/syscalls-table/blob/master/do_all_tables.sh#L25 but removed from the repository!
https://raw.githubusercontent.com/hrw/syscalls-table/208745c117be280999cafea70affc7c94e2a627a/list-syscalls.c

I think the code to automatically generate it with  ` ./generate-list-syscalls.sh  > list-syscalls.c` need to added to `do_all_tables.sh` script.

**Comment by hrw** [comment]
list-syscalls.c is generated when needed. "make clean" removes it.

And the proper way of generating it is "make clean;make KERNELSRC=path_to_linux_sources"
