### ISSUE TITLE
IA64 table creation

### ISSUE THREAD

**Issue by acerv** [hrw/syscalls-table#100]
Hi,
I'm currently working on the [Linux Test Project](https://github.com/linux-test-project/ltp) as a developer. One of our current goals is to automatically generate a [syscalls.h](https://github.com/linux-test-project/ltp/tree/master/include/lapi/syscalls) fallback file via shell script, in order to simplify its updating process when new syscalls are added into the Linux Kernel. We found your project interesting and I was taking a look at the `update-table.sh` script, in order to start from something existing and with a good code base.
I managed to create a script based on your approach, but I encountered one issue while generating the ia64 syscalls file. Inside the project I don't see any reference to this architecture, both in [update-table.sh](https://github.com/hrw/syscalls-table/blob/master/scripts/update-tables.sh) script and [architectures-present-in-kernel.txt](https://github.com/hrw/syscalls-table/blob/master/data/architectures-present-in-kernel.text) file. But I can clearly see the [syscall-ia64](https://github.com/hrw/syscalls-table/blob/master/data/tables/syscalls-ia64) file that has been generated by them.
Could you please clarify how this file has been generated?

Thanks,
Andrea

**Comment by hrw** [comment]
This project contains syscalls for all architectures which (at some point) were supported by Linux kernel.

Support for avr32, blackfin, c6x, cris, frv, h8300, ia64, m32r, metag, mn10300, nds32, score, sh64, tile, tile64 and unicore32 was removed at some point and those architectures are no longer supported by Linux. I keep their data in case someone needs (entries specific to removed architectures are removed).

You can use files in data/ directory directly (like systemd project does). They are simple text or tsv files:

- [architectures-present-in-kernel.text](https://github.com/hrw/syscalls-table/blob/master/data/architectures-present-in-kernel.text) lists all architectures present in latest Linux kernel
- [removed-names.text](https://github.com/hrw/syscalls-table/blob/master/data/removed-names.text) keeps all names which are present in Linux kernel but are not handled (like all those OSF_ ones on Alpha)
- [syscall-names.text](https://github.com/hrw/syscalls-table/blob/master/data/syscall-names.text) keeps names of all system calls supported and handled in Linux kernel
- tables/* are TAB separated files

**Comment by acerv** [comment]
Thank you very much for the explanation.
Andrea

**Comment by hrw** [comment]
Note that there is also Python 'system_calls' package providing that data.

There was also one in Rust but I do not track its development.
