### ISSUE TITLE
How to help link points to wrong repo

### ISSUE THREAD

**Issue by charliemirabile** [hrw/syscalls-table#104]
Since latest commit fbf0649 ("use tables-common to unify my tables") the specific link to this repo and the suggestion that people say if they are using this project in issue #12 that was present before has been removed:
https://github.com/hrw/syscalls-table/commit/fbf06493226442344251bbface8a7cf27bfeed2d#diff-2d1d8eb95b7341ac68642cc6a2eab34340e8bdeda5222bc061e55ca7a42fc726L147-L156
```html
<h2>How to help</h2>
    <p>
    Sources used to generate table are available in <a
    href="https://github.com/hrw/syscalls-table">git repository at github</a>.
    Patches are always welcomed.
    </p>
    <p>
    If this table helped you in some project then please leave a comment in
    <a href="https://github.com/hrw/syscalls-table/issues/12">issue on GitHub</a>.
    </p>
```

Instead, the common table has:
https://github.com/hrw/tables-common/blob/eeffc4e095015d9885e8ce708529307f08ddeb45/author-tables-help.inc.j2#L14-L19
```html
<h2>How to help</h2>
    <p>
    Sources used to generate table are available in <a
    href="https://github.com/hrw/arm-socs-table">git repository at github</a>.
    Patches are always welcomed.
    </p>
```

which includes an incorrect link to the arm-soc-table repo and no mention of issue #12.

**Comment by hrw** [comment]
Thanks for catching it. Will fix.

**Comment by hrw** [comment]
Aaaand fixed ;D

Thanks again for reporting.
