### ISSUE TITLE
DEAD_SYSCALLS unintentionally includes clock_* syscalls

### ISSUE THREAD

**Issue by koalo** [hrw/syscalls-table#16]
Since DEAD_SYSCALLS includes "lock", the regular expression also matches all clock_* syscall.
This is probably usually unnoticed, because missing syscalls are not removed from the syscall-names.text. However, for newly introduced syscalls that only partially match the DEAD_SYSCALLS, this might result in problems.

I only noticed that because for my special purpose I need a syscall-names.text that ONLY covers the syscalls for a specific version, so I cleared that file and ran the scripts.

**Comment by hrw** [comment]
Thanks @koalo for reporting that issue.

I rewrote part which gathers new system calls and three entries appeared:


- landlock_add_rule
- landlock_create_ruleset
- landlock_restrict_self
 

Earlier they were dropped due to 'lock' in names.
