### ISSUE TITLE
Does riscv32 have ppoll?

### ISSUE THREAD

**Issue by yuwata** [hrw/syscalls-table#17]
I am not familiar with the arch, but recently we receive the following comment https://github.com/systemd/systemd/pull/19858#issuecomment-861132188.

syscalls-riscv32 says ppoll is defined, and ppoll_time64 (and *_time64) is not. But if I understand code correctly, it seems that *_time64 are defined in include/uapi/asm-generic/unistd.h.

**Comment by hrw** [comment]
Will check later today.

**Comment by yuwata** [comment]
Thanks.

**Comment by hrw** [comment]
Ok, looks like riscv32 tables are wrong as I have some more entries to fix.

**Comment by yuwata** [comment]
Thank you for the quick fix!

**Comment by hrw** [comment]
Table generation fixed, new page online.
