### ISSUE TITLE
LoongArch support

### ISSUE THREAD

**Issue by xen0n** [hrw/syscalls-table#19]
Hi,

We (the open-source Loongson ecosystem volunteers and the Loongson Corporation) are trying to port Linux to the LoongArch architecture, and we've seen that systemd depends on this project for its syscall data. The LoongArch Linux port is not upstream yet, but is already submitted for review, and it uses fully asm-generic syscall numbering (the syscalls should be the same as RISC-V).

How do we go forward to add support for this architecture?

P.S. Useful links:

* [initial port posted on linux-arch](https://www.spinics.net/lists/linux-arch/msg72300.html),
* [official documentation translated by Loongson](https://github.com/loongson/LoongArch-Documentation),
* the [binutils](https://github.com/loongson/binutils-gdb), [gcc](https://github.com/loongson/gcc), [glibc](https://github.com/loongson/glibc) ports,
* the [loongarch64 GitHub org](https://github.com/loongarch64) where some of the packages get ported and reviewed before submission to upstream.

**Comment by hrw** [comment]
You may run "make KERNSRC=path/to/your/kernel/tree" and then send PR adding tables/syscalls-loongarch file.
