### ISSUE TITLE
missing `*statat` syscalls

### ISSUE THREAD

**Issue by flysand7** [hrw/syscalls-table#31]
Noticed that arm64 didn't have any `stat` syscalls

**Comment by hrw** [comment]
Arm64 has those \*stat\* system calls:

- fstat
- fstatfs
- newfstatat
- statfs
- statx

If you look at [stat 2 manpage](https://www.man7.org/linux/man-pages/man2/stat.2.html) you notice how \*stat\* system calls were changing:

> The glibc stat() wrapper function hides these details from   applications, invoking the most recent version of the system call provided by the kernel, and repacking the returned information if required for old binaries.
> 
> On modern 64-bit systems, life is simpler: there is a single stat() system call and the kernel deals with a stat structure that contains fields of a sufficient size.
> 
> The underlying system call employed by the glibc fstatat() wrapper function is actually called fstatat64() or, on some architectures, newfstatat().

Several modern architectures never got support for older system calls because there were already deprecated.

**Comment by flysand7** [comment]
I guess I should specify that only `fstatat` is missing from the table

**Comment by flysand7** [comment]
It seems like you are right, from reading linux source code it does seem like there's `fstatat64` and `newfstatat64`.

Though one slight thing I noticed is that `fstatat64` seems to be present on ARM64, which is like one of those architectures that seems to be trying to cut down on the number of syscalls it has. Probably because linux uses the new way (asm-generic/unistd.h) to declare syscall numbers (rather than .tbl files).

I'm closing this issue as I feel like I got an answer, though if you feel like addressing that last concern, please don't hesitate to reply :)

Thanks for making that webpage, really helped!

**Comment by hrw** [comment]
If system call name ends with "64" then (most of times) it is 32-bit architectures only call.

TBL files were added to make it easier to gather which system calls are present on supported architectures. 

For "new" architectures one, unified, list is used. Without deprecated system calls.
