### ISSUE TITLE
Hide syscalls with -1

### ISSUE THREAD

**Issue by oxwivi** [hrw/syscalls-table#9]
Will let us see more or less accurate list of currently supported syscalls.

**Comment by hrw** [comment]
You mean hiding "-1" values? 

Every syscall is present on at least one architecture.

**Comment by oxwivi** [comment]
No, hide syscalls with even a single "-1" value for any arch. That'll give a comprehensive list of syscalls that's supported across the board.

**Comment by hrw** [comment]
It does not work that way.

Several syscalls are legacy/deprecated and as such are not supported on newer architectures but stay supported on older ones.

**Comment by oxwivi** [comment]
I know, you mentioned it on your blog post. I'm asking for a feature to hide those syscalls to see which of them are supported across the board, on all archs.

**Comment by hrw** [comment]
patches welcome but this has to be optional

**Comment by hrw** [comment]
I plan to add some statistics on the bottom of page.
