### ISSUE TITLE
6.11.0: pytest fails in `system_calls/tests/test_syscalls.py::test_alpha_osf_fuser` unit

### ISSUE THREAD

**Issue by kloczek** [hrw/syscalls-table#97]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-system-calls-6.11.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-system-calls-6.11.0-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network' --exit-0-if-no-units
============================= test session starts ==============================
platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/tkloczko/rpmbuild/BUILD/syscalls-table-6.11.0
collected 6 items

system_calls/tests/test_syscalls.py ....F.                               [100%]

=================================== FAILURES ===================================
_____________________________ test_alpha_osf_fuser _____________________________

self = {}, syscall_name = 'osf_fuser', arch = 'alpha'

    def get(self, syscall_name: str, arch: str = "") -> int:  # type: ignore
        """Returns number for requested system call.
        Architecture can be provided by second argument (optional, host
        architecture would be used by default).
        """
        if arch == "":
            arch = self.default_arch

        try:
>           return self.syscalls["archs"][arch][syscall_name]
E           KeyError: 'osf_fuser'

../../BUILDROOT/python-system-calls-6.11.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/system_calls/__init__.py:138: KeyError

During handling of the above exception, another exception occurred:

    def test_alpha_osf_fuser():
>       assert 243 == syscalls.get("osf_fuser", "alpha")

system_calls/tests/test_syscalls.py:27:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = {}, syscall_name = 'osf_fuser', arch = 'alpha'

    def get(self, syscall_name: str, arch: str = "") -> int:  # type: ignore
        """Returns number for requested system call.
        Architecture can be provided by second argument (optional, host
        architecture would be used by default).
        """
        if arch == "":
            arch = self.default_arch

        try:
            return self.syscalls["archs"][arch][syscall_name]
        except KeyError:
            if syscall_name not in self.syscalls["names"]:
>               raise NoSuchSystemCall
E               system_calls.NoSuchSystemCall

../../BUILDROOT/python-system-calls-6.11.0-2.fc37.x86_64/usr/lib/python3.10/site-packages/system_calls/__init__.py:141: NoSuchSystemCall
=========================== short test summary info ============================
FAILED system_calls/tests/test_syscalls.py::test_alpha_osf_fuser - system_cal...
========================= 1 failed, 5 passed in 0.08s ==========================
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package            Version
------------------ -----------
build              1.2.2
distro             1.9.0
exceptiongroup     1.1.3
importlib_metadata 8.0.0
iniconfig          2.0.0
installer          0.7.0
packaging          24.0
pluggy             1.5.0
pyproject_hooks    1.0.0
pytest             8.2.2
python-dateutil    2.9.0.post0
setuptools         74.1.2
tokenize_rt        6.0.0
tomli              2.0.1
wheel              0.44.0
zipp               3.19.2
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by hrw** [comment]
Thanks. Have to add running pytest to github actions.

6.11.1 later today.

**Comment by hrw** [comment]
6.11.1 tagged and on it's way to pypi

**Comment by kloczek** [comment]
Just tested 6.11.1 and now all look good
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-system-calls-6.11.1-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-system-calls-6.11.1-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network'
============================= test session starts ==============================
platform linux -- Python 3.10.14, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/tkloczko/rpmbuild/BUILD/syscalls-table-6.11.1
collected 5 items

system_calls/tests/test_syscalls.py .....                                [100%]

============================== 5 passed in 0.05s ===============================
```
Thank you
---

As long you've started using GH actions may I as for yet another thing?
is it possible to start making github releases?🤔
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://github.com/getmoto/py-partiql-parser/commit/a58a3783
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by hrw** [comment]
6.11.1 done by hand, will look into automation later

**Comment by kloczek** [comment]
Thank you 👍
